//Auth

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

//APPLICATIONS
export const SUBMIT_NEW_APPLICATION_REQUEST = 'SUBMIT_NEW_APPLICATION_REQUEST';
export const SUBMIT_NEW_APPLICATION_SUCCESS = 'SUBMIT_NEW_APPLICATION_SUCCESS';
export const SUBMIT_NEW_APPLICATION_FAILURE = 'SUBMIT_NEW_APPLICATION_FAILURE';
