//Auth

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

//APPLICATIONS
export const SUBMIT_NEW_APPLICATION_REQUEST = 'SUBMIT_NEW_APPLICATION_REQUEST';
export const SUBMIT_NEW_APPLICATION_SUCCESS = 'SUBMIT_NEW_APPLICATION_SUCCESS';
export const SUBMIT_NEW_APPLICATION_FAILURE = 'SUBMIT_NEW_APPLICATION_FAILURE';

export const GET_ALL_APPLICATIONS_REQUEST = 'GET_ALL_APPLICATIONS_REQUEST';
export const GET_ALL_APPLICATIONS_SUCCESS = 'GET_ALL_APPLICATIONS_SUCCESS';
export const GET_ALL_APPLICATIONS_FAILURE = 'GET_ALL_APPLICATIONS_FAILURE';

export const FETCH_APPLICATION_REQUEST = 'FETCH_APPLICATION_REQUEST';
export const FETCH_APPLICATION_SUCCESS = 'FETCH_APPLICATION_SUCCESS';
export const FETCH_APPLICATION_FAILURE = 'FETCH_APPLICATION_FAILURE';
